#!/usr/bin/env python

# Credit: cubercsl https://github.com/cubercsl/repo/blob/master/scripts/add_aur_pkg

"""
Usage: add_aur_pkg aur_pkg...

"""
import argparse
import os

from pathlib import Path

ROOT = Path(__file__).parent
REPO = Path(ROOT, 'moody')


def usage():
    print(__doc__)


TEMPLATE = '''
maintainers:
  - github: moodyhunter

pre_build_script: aur_pre_build(maintainers={maintainers})

post_build: aur_post_build

update_on:
  - source: aur
    aur: {pkg_name}

# vim:set ts=4 sw=2 et:
'''


def add_pkg(pkg_name, maintainers):
    print(pkg_name, maintainers)
    os.makedirs(Path(REPO, pkg_name), exist_ok=True)

    path = Path(REPO, pkg_name, 'lilac.yaml')
    content = TEMPLATE.format(pkg_name=pkg_name, maintainers=repr(maintainers))

    with open(path, 'w') as f:
        f.write(content)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Add an AUR Pakage in repo")
    parser.add_argument('pkg_name')
    args = parser.parse_args()
    add_pkg(args.pkg_name, ["Moody"])
